@bearer_token = 
@key = 

### put using managed identity (oauth2)
PUT https://stnexusdev11.blob.core.windows.net/landing/{{$guid}}.json HTTP/1.1
Authorization: Bearer {{bearer_token}}
x-ms-version: 2019-12-12
x-ms-blob-type: BlockBlob
Content-Length: 19

This is a test file

### get using oauth2
GET https://stnexusdev11.blob.core.windows.net/?comp=list&maxresults=3 HTTP/1.1
x-ms-version: 2018-03-28
Authorization: Bearer {{bearer_token}}

### get specific file using oauth2
GET https://stnexusdev11.blob.core.windows.net/landing/3a359627-bf29-4300-adb3-bfc8691e03bb.json HTTP/1.1
x-ms-version: 2018-03-28
Authorization: Bearer {{bearer_token}}

###
PUT https://apim-nexus-westeu-dev-01.azure-api.net/blob-api/put/{{$guid}}.json HTTP/1.1
Host: apim-nexus-westeu-dev-01.azure-api.net
Subscription-Key-Header-Name: {{key}}

{
	"vehicleType": "train",
	"maxSpeed": 125,
	"avgSpeed": 90,
	"speedUnit": "mph"
}
